.github/workflows/cicd.yml, Dockerfile, build.gradle, src/main/java/com/goormthom/danpoong/reboot/config/SwaggerConfig.java, src/main/java/com/goormthom/danpoong/reboot/controller/HealthController.java
- Resolves : #3
1. CICD Workflow 추가
2. 스웨거 의존성 및 Configuration 구현
3. Server Health Check을 위한  HealthController 구현
=> [ Feature ] - CI/CD 적용

.github/workflows/cicd.yml
- Resolves : #5 
CICD Worlkflow Error에 대한 작업을 진행하였습니다. -> Shell Script Error Fix
- 
=> [ Bug ] - CICD Workflow Error 

.gitignore, src/test/java/com/goormthom/danpoong/reboot/RebootApplicationTests.java
- Resolves : #8
1. .gitignore에서 *.yml 숨김 처리
2. 테스트코드 주석처리
- 
=> [ Bug ] - CICD 중 ./gradlew build 오류 

src/main/java/com/goormthom/danpoong/reboot/controller/UserController.java, src/main/java/com/goormthom/danpoong/reboot/domain/Meal.java, src/main/java/com/goormthom/danpoong/reboot/domain/User.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateMealRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateOnBoardingRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateRegisterRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/service/oauth/LoginByKakaoService.java, src/main/java/com/goormthom/danpoong/reboot/service/user/CreateOnBoardService.java, src/main/java/com/goormthom/danpoong/reboot/service/user/CreateRegisterService.java, src/main/java/com/goormthom/danpoong/reboot/usecase/user/CreateOnBoardingUseCase.java, src/main/java/com/goormthom/danpoong/reboot/usecase/user/CreateRegisterUseCase.java, src/main/java/com/goormthom/danpoong/reboot/util/OAuth2Util.java
- Resolves : #14 
- 소셜로그인 이메일을 안받아서 추가
- 온보딩 저장
- 근로계약서 저장
=> [ Feature ] - 소셜로그인, 온보딩, 근로계약서 api

src/main/java/com/goormthom/danpoong/reboot/controller/AuthController.java, src/main/java/com/goormthom/danpoong/reboot/controller/UserController.java, src/main/java/com/goormthom/danpoong/reboot/controller/docs/AuthDocs.java, src/main/java/com/goormthom/danpoong/reboot/controller/docs/UserDocs.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateMealRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateOnBoardingRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateRegisterRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/JwtTokenDto.java
- Resolves : #17
- Controller 및 Dto에 관한 Swagger 작업 진행
=> [ Refactor ] - API Docs(Swagger) 작업

build.gradle, src/main/java/com/goormthom/danpoong/reboot/controller/AnalysisController.java, src/main/java/com/goormthom/danpoong/reboot/controller/docs/AnalysisDocs.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/JournalResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/MissionListResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/RemainPeriodResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/repository/ChatRoomRepository.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/JournalService.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/MissionListService.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/RemainPeriodService.java, src/main/java/com/goormthom/danpoong/reboot/usecase/analysis/JournalUseCase.java, src/main/java/com/goormthom/danpoong/reboot/usecase/analysis/MissionListUseCase.java, src/main/java/com/goormthom/danpoong/reboot/usecase/analysis/RemainPeriodUseCase.java
- Resolves : #20
- 출근 일 수 및 사용자 직급 반환
- 주차별 업무일지 리스트 반환
=> [ Feature ] - 통계 관련 API 구현

build.gradle, src/main/java/com/goormthom/danpoong/reboot/config/S3Config.java, src/main/java/com/goormthom/danpoong/reboot/constant/Constants.java, src/main/java/com/goormthom/danpoong/reboot/controller/ChatController.java, src/main/java/com/goormthom/danpoong/reboot/domain/Chat.java, src/main/java/com/goormthom/danpoong/reboot/domain/type/EChatType.java, src/main/java/com/goormthom/danpoong/reboot/domain/type/ESpeaker.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateChatRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/PromaDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/ReadChatAiResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/ReadChatResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/ReadChatRoomResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/ReadChatUserResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/exception/ErrorCode.java, src/main/java/com/goormthom/danpoong/reboot/repository/ChatRepository.java, src/main/java/com/goormthom/danpoong/reboot/repository/ChatRoomRepository.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/CreateChatService.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/ReadChatRoomService.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/ReadChatService.java, src/main/java/com/goormthom/danpoong/reboot/usecase/chat/CreateChatUseCase.java, src/main/java/com/goormthom/danpoong/reboot/usecase/chat/ReadChatRoomUseCase.java, src/main/java/com/goormthom/danpoong/reboot/usecase/chat/ReadChatUseCase.java, src/main/java/com/goormthom/danpoong/reboot/util/OAuth2Util.java, src/main/java/com/goormthom/danpoong/reboot/util/PromaUtil.java, src/main/java/com/goormthom/danpoong/reboot/util/S3Util.java
- 채팅방 list api
- 채팅내역 list api
- s3설정
- ai에서 답변을 주고 받는 api
=> [ Feature ] - 채팅방 관련 api

src/main/java/com/goormthom/danpoong/reboot/controller/ChatController.java, src/main/java/com/goormthom/danpoong/reboot/controller/docs/AnalysisDocs.java, src/main/java/com/goormthom/danpoong/reboot/controller/docs/ChatDocs.java
=> Docs: 스웨거 명세서 추가

src/main/java/com/goormthom/danpoong/reboot/batch/DynamicTaskScheduler.java, src/main/java/com/goormthom/danpoong/reboot/config/SchedulerInitializer.java, src/main/java/com/goormthom/danpoong/reboot/config/SchedulingConfig.java, src/main/java/com/goormthom/danpoong/reboot/repository/ChatRoomRepository.java, src/main/java/com/goormthom/danpoong/reboot/repository/UserRepository.java, src/main/java/com/goormthom/danpoong/reboot/service/user/CreateRegisterService.java
- Resolves : #27
- 사용자의 각기 다른 출근 시간에 따른 동적 스케줄러 구현
=> [ Feature ] - 유동 업무 스케줄러 구현 

src/main/java/com/goormthom/danpoong/reboot/controller/AnalysisController.java, src/main/java/com/goormthom/danpoong/reboot/controller/docs/AnalysisDocs.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/AllAnalysisResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/AllAnalysisService.java, src/main/java/com/goormthom/danpoong/reboot/usecase/analysis/AllAnalysisUseCase.java
- Resolves : #30
- 전체 분석 값을 한 번에 내려준 api 추가 및 명세서 수정
=> [ Refactor ] - Analysis API 수정 및 추가

src/main/java/com/goormthom/danpoong/reboot/dto/response/LastChatInfo.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/ReadChatRoomResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/ReadChatRoomService.java
=> HotFix: 채팅방 리스트 반환값 수정

Dockerfile
- Resolves : #33
- DockerFile 수정
=> [ Bug ] - 배포 시, JVM 시간 UTC 설정 이슈

src/main/java/com/goormthom/danpoong/reboot/exception/ErrorCode.java, src/main/java/com/goormthom/danpoong/reboot/exception/GlobalExceptionHandler.java
=> HotFix - 에러코드 추가 

src/main/java/com/goormthom/danpoong/reboot/controller/ChatController.java
=> Fix: 이미지 request방식 수정

src/main/java/com/goormthom/danpoong/reboot/controller/ChatController.java
=> HotFix: 이미지 오류

src/main/java/com/goormthom/danpoong/reboot/exception/GlobalExceptionHandler.java
=> HotFix: 에러구분 추가

src/main/java/com/goormthom/danpoong/reboot/batch/DynamicTaskScheduler.java, src/main/java/com/goormthom/danpoong/reboot/domain/type/EChatType.java, src/main/java/com/goormthom/danpoong/reboot/domain/type/EMissionStatus.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/MissionListResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/repository/ChatRepository.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/MissionListService.java
- Resolves : #39
- MissionList Dto 반환값 추가 및 수정
=> [ Refactor ] - 미션 List Dto 반환값 수정

src/main/java/com/goormthom/danpoong/reboot/batch/DynamicTaskScheduler.java
- Resolves : #38
- 동적 스케줄러 메세지 포맷 수정
=> [ Refactor ] - 스케줄러 메세지 포맷 수정

src/main/java/com/goormthom/danpoong/reboot/controller/ChatController.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/CreateChatService.java, src/main/java/com/goormthom/danpoong/reboot/usecase/chat/CreateChatUseCase.java, src/main/java/com/goormthom/danpoong/reboot/util/S3Util.java
=> Fix: 이미지 버그 수정

src/main/java/com/goormthom/danpoong/reboot/controller/AnalysisController.java, src/main/java/com/goormthom/danpoong/reboot/controller/docs/AnalysisDocs.java, src/main/java/com/goormthom/danpoong/reboot/domain/type/EMissionStatus.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/CalendarDetailResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/CalendarItemResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/CalendarResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/repository/ChatRepository.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/CalendarDetailService.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/CalendarService.java, src/main/java/com/goormthom/danpoong/reboot/usecase/analysis/CalendarDetailUseCase.java, src/main/java/com/goormthom/danpoong/reboot/usecase/analysis/CalendarUseCase.java
- Resolves : #36
- 일자별 업무들 상세보기 기능 구현
- 캘리더 업무별 조회 기능 구현
=> [ Feature ] - 캘린더 조회 및 날짜별 상세 조회 구현

src/main/java/com/goormthom/danpoong/reboot/service/chat/CreateChatService.java, src/main/java/com/goormthom/danpoong/reboot/usecase/chat/CreateChatUseCase.java
=> Fix: 채팅창 내역 응답 통일

src/main/java/com/goormthom/danpoong/reboot/domain/User.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateOnBoardingRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/UserDetailDto.java, src/main/java/com/goormthom/danpoong/reboot/service/user/ReadUserService.java
=> Feat: 유저 온보딩 영어이름 저장, 조회 추가

src/main/java/com/goormthom/danpoong/reboot/domain/type/EChatType.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/CalendarDetailResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/MissionListResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/MissionListService.java
- Resolves : #50
-  MissionListResponseDto 시간 포맷팅 수정
=>  [ Refactor ] - Dto 시간 포맷팅 수정

src/main/java/com/goormthom/danpoong/reboot/config/SchedulingConfig.java
- Resolves : #52
- EC2 인스턴스 업스케일링에 따른 스케줄러 쓰레드풀 사이즈 증가
=> [ Refactor ] - 스케줄러 쓰레드풀 수정

src/main/java/com/goormthom/danpoong/reboot/domain/User.java, src/main/java/com/goormthom/danpoong/reboot/dto/request/CreateRegisterRequestDto.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/RemainPeriodService.java
- Resolves : #54
- 사용자 근로계약서 작성 로직 수정
- RemainPeriodService 오류 해결
=> [ Bug ] - RemainPeriodService 오류

src/main/java/com/goormthom/danpoong/reboot/service/analysis/CalendarService.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/MissionListService.java
- Resolves : #56
- 오늘 날짜가 아닌 미션을 반환하는 문제를 해결하였습니다.
=> [ Bug ] - Mission List 외부활동 반환 버그 

src/main/java/com/goormthom/danpoong/reboot/dto/response/ReadChatResponseDto.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/CreateChatService.java
=> HotFix: 이미지 출력 형태 추가

src/main/java/com/goormthom/danpoong/reboot/constant/Constants.java, src/main/java/com/goormthom/danpoong/reboot/domain/type/EChatType.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/ReadChatRoomService.java, src/main/java/com/goormthom/danpoong/reboot/service/scheduler/LeaveSchedulerService.java, src/main/java/com/goormthom/danpoong/reboot/service/scheduler/MealSchedulerService.java, src/main/java/com/goormthom/danpoong/reboot/service/scheduler/OutsideSchedulerService.java
=> Refactor: 스케줄러 자동생성 메세지 구문변경

src/main/java/com/goormthom/danpoong/reboot/domain/type/EChatType.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/MissionListService.java
- Resolves : #62
- Fix NullPointerException
=>  [ Bug ] - MissionList NullPointerException

src/main/java/com/goormthom/danpoong/reboot/repository/ChatRoomRepository.java, src/main/java/com/goormthom/danpoong/reboot/service/scheduler/MealSchedulerService.java
- Resolves : #70
- 불필요한 메서드 삭제
- 메시지 관련 로직 배치 처리를 통해 성능 개선
=> [ Refactor ] - MealScheduler 성능 개선

src/main/java/com/goormthom/danpoong/reboot/controller/ChatController.java, src/main/java/com/goormthom/danpoong/reboot/controller/docs/ChatDocs.java, src/main/java/com/goormthom/danpoong/reboot/domain/Chat.java, src/main/java/com/goormthom/danpoong/reboot/domain/type/EChatType.java, src/main/java/com/goormthom/danpoong/reboot/dto/response/PromaMissionDto.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/CalendarService.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/MissionListService.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/CreateChatService.java, src/main/java/com/goormthom/danpoong/reboot/usecase/chat/CreateChatUseCase.java, src/main/java/com/goormthom/danpoong/reboot/util/PromaUtil.java, src/main/resources/application.yml
=> Feat: AI 자동 채팅 기능 추가

src/main/java/com/goormthom/danpoong/reboot/service/user/CreateRegisterService.java
- Resolves : #73
- 근로계약서 Service 트랜젹션 문제인 것으로 보여, 임시 Logging 추가
- 트랜잭션 로깅 확인 후, 로깅 제거 예정
=> [ Bug ] - 근로계약서 내용이 저장안되는 문제

src/main/java/com/goormthom/danpoong/reboot/domain/ChatRoom.java, src/main/java/com/goormthom/danpoong/reboot/service/user/CreateRegisterService.java
=> Refactor: 근로계약서 작성시 자유채팅방 생성

src/main/java/com/goormthom/danpoong/reboot/domain/type/EChatType.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/CalendarService.java
=> Fix: 캘린더 오류

src/main/java/com/goormthom/danpoong/reboot/batch/MealScheduler.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/CalendarService.java, src/main/java/com/goormthom/danpoong/reboot/service/analysis/MissionListService.java, src/main/java/com/goormthom/danpoong/reboot/service/chat/CreateChatService.java, src/main/java/com/goormthom/danpoong/reboot/service/scheduler/MealSchedulerService.java
=> Fix: 시연용 스케쥴러

src/main/java/com/goormthom/danpoong/reboot/service/chat/ReadChatService.java
=> Fix: 채팅방 시간 수정

src/main/java/com/goormthom/danpoong/reboot/dto/response/ReadChatRoomResponseDto.java
=> Fix: 시연용 스케줄러

src/main/java/com/goormthom/danpoong/reboot/service/chat/CreateChatService.java
=> Fix: 채팅 답변 성공 플래그 수정
